### PR TITLE
remove git from the snap

### PR DESCRIPTION
**Pull request by come-maiz**

### CODE REVIEW

**Comment by joshuacaplan** [comment]
When removing git on my local installation of branch-diff. I receive this error on Ubuntu 16.04.03

```bash: git: command not found
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: git command [git merge-base dev master] exited with code 127
    at ChildProcess.child.on (/snap/branch-diff/x1/lib/node_modules/branch-diff/node_modules/gitexec/gitexec.js:23:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

Adding git back solves the problem. This is the same error which led me to add git in the first place.

**Comment by come-maiz** [comment]
ahh, I see, good catch @LaughingLove.
I will close this PR. What you need is to add git to build-packages. Do you have time to do that, or would you want me to make a different pr?

**Comment by come-maiz** [comment]
sorry, stage-packages, not build-packages.

**Comment by joshuacaplan** [comment]
No @elopio I will go ahead and add it to the stage-packages.

**Comment by come-maiz** [comment]
Awesome @LaughingLove, it's looking nice.

**Pull request closed without merging**
